[theme]
base="light"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[theme.dark]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#262730"
secondaryBackgroundColor="#1A1A1A"
textColor="#FFFFFF"